jeupromo/games/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import TemplateView
# from . import views
from .views import *
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
app_name = 'games'

urlpatterns = [
    path('home', home, name = 'home'),

    path('players', PlayerList.as_view(), name='players'),
    path('', GameList.as_view(), name='games'),
    path('player-create/', PlayerCreate.as_view(), name='player-create'),
    path('player-detail/<int:pk>/', PlayerDetail.as_view(), name='player-detail'),
    path('player-update/<int:pk>/', PlayerUpdate.as_view(), name='player-update'),
    path('player-delete/<int:pk>/', PlayerDelete.as_view(), name='player-delete'),
    
    path('reward-create/', RewardCreate.as_view(), name='reward-create'),
    path('reward-detail/<int:pk>/', RewardDetail.as_view(), name='reward-detail'),
    path('rewards', RewardList.as_view(), name='rewards'),
    path('reward-update/<int:pk>/', RewardUpdate.as_view(), name='reward-update'),
    path('reward-delete/<int:pk>/', RewardDelete.as_view(), name='reward-delete'),

    path('promotion-create/', PromotionCreate.as_view(), name='promotion-create'),
    path('promotion-detail/<int:pk>', PromotionDetail.as_view(), name='promotion-detail'),
    path('promotions', PromotionList.as_view(), name='promotions'),
    path('promotion-update/<int:pk>', PromotionUpdate.as_view(), name='promotion-update'),
    path('promotion-delete/<int:pk>', PromotionDelete.as_view(), name='promotion-delete'),
    path('base', base, name='base'),
    path('test', test, name='test'),
    url(r'^login/$', login_user, name = 'login'),
    url(r'^main/$', main, name="main"),
    url(r'^signup/$', signup, name='signup'),
    url(r'logout', LogoutView.as_view(template_name="games/logout.html"), name='logout'),
    path('gamesChoice', GamesChoice.as_view(), name='gamesChoice'),
    path('scratch', scratch, name='scratch')
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jeupromo/jeupromo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^games/', include('games.urls')),
]
#  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

jeupromo/games/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User




class Games(models.Model):
    label = models.CharField(max_length=150, verbose_name='libellé')
    game_type = models.CharField(max_length=150, verbose_name='type de jeu')
    game_logo = models.ImageField("logo jeu", null=True, blank=True, upload_to="img/")
    description = models.TextField(max_length=150 )

    def __str__(self):
        return self.label

    class Meta:
        verbose_name = "Jeu"
        verbose_name_plural = "Jeux"


class Player(models.Model):
    GENDER_CHOICES = (
        ( 'Mr.', 'Monsieur'),
        ( 'Mme', 'Madame'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    auto_increment_id = models.AutoField(primary_key=True, verbose_name = 'id')
    pseudo = models.CharField(max_length=100, verbose_name= 'pseudo', unique=True)
    gender = models.CharField(max_length=20, verbose_name= 'civilité', choices=GENDER_CHOICES )
    avatar = models.ImageField("avatar", null=True, blank=True, upload_to="avatar/")
    dateNaissance = models.DateField(null=True)
   

    def __str__(self):
        return self.pseudo

    class Meta:
        verbose_name = "Joueur"

class Administrator(Player):
    

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Gestionnaire"

class Promotion(models.Model):
    name = models.CharField(max_length=200)
    date_start = models.DateField(null=True)
    date_end = models.DateField(null=True)
    administrator = models.ForeignKey(Administrator, on_delete=models.CASCADE)
    reward = models.ManyToManyField(Games, through='PromotionGames')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Opération Promotionnelle"
        verbose_name_plural = "Opérations Promotionnelles"



class Reward(models.Model):
    label = models.CharField(max_length=150, verbose_name='libellé')
    value = models.IntegerField(verbose_name='valeur')

    def __str__(self):
        return self.label + ' ' + str(self.value)

    class Meta:
        verbose_name = "Gain"


class Session(models.Model):
    game = models.ForeignKey(Games, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    # datetime = models.DateTimeField(default=timezone.now())
    datetime = models.DateTimeField(auto_now_add=True)
    reward = models.ForeignKey(Reward, on_delete=models.CASCADE)
    result = models.CharField(max_length=150)

    def __str__(self):
        return self.player.pseudo + ' ' + self.game.label + ' ' + str(self.datetime) + ' ' + self.reward.label + ' ' + self.result

    class Meta:
        verbose_name = "Partie"

#PRG stand for Promotion Rewards Games
class PromotionGames(models.Model):
    promotion = models.ForeignKey(Promotion, on_delete=models.CASCADE)
    game = models.ForeignKey(Games, on_delete=models.CASCADE)
    reward = models.ForeignKey(Reward, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = "Opération Promotionnelle Jeu(x) Gain(s)"
        verbose_name_plural = "Opérations Promotionnelles Jeu(x) Gain(s)"

jeupromo/games/forms.py
from django.forms import ModelForm, FileInput, EmailInput, TextInput, DateInput
from .models import *
from django import forms


class PlayerForm(ModelForm):
    class Meta :
        model = Player
        fields = '__all__'
        widgets = {
            'name': TextInput(attrs={
                'type':"text", 
                'id':"LastName",
                'name':"LastName",
                'placeholder':"Nom",
                'class':"input-xlarge"
                              }),
            'firstname': TextInput(attrs={
                'type':"text", 
                'id':"FirstName",
                'name':"FirstName",
                'placeholder':"Prénom",
                'class':"input-xlarge"
                              }),
            'email': EmailInput(attrs={
                'type':"email", 
                'id':"email",
                'name':"email",
                'placeholder':"Adresse E-mail",
                'class':"input-xlarge"
                              }),
            'dateNaissance': DateInput(attrs={
                'type':"date", 
                'id':"dateNaissance",
                'name':"dateNaissance",
                'placeholder':"Date de Naissance",
                'class':"input-xlarge"
                              }),
            'pseudo': TextInput(attrs={
                'type':"text", 
                'id':"Pseudo",
                'name':"Pseudo",
                'placeholder':"Pseudo",
                'class':"input-xlarge"
                              }),
            # 'img_player': FileInput(attrs={
            #     'type':"file", 
            #     'name':"LastName",
            #     'placeholder':"Nom",
            #     'class':"btn btn-outline-primary"
            #                   }),
            
        }

class PromotionForm(ModelForm):
    class Meta:
        model = Promotion
        fields = "__all__"
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'date_start': DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'date_end': DateInput(attrs={'type': 'date','class': 'form-control'}),
            'administrator': TextInput(attrs={'class': 'form-control'}),
            
        }

class RewardForm(ModelForm):
    class Meta:
        model = Reward
        fields = "__all__"

class LoginForm(ModelForm):
    class Meta:
        model = User
        fields = "__all__"

class LogoutForm(forms.Form):
    pass

class UserForm(ModelForm):
    class Meta :
        model = User
        fields = '__all__'

jeupromo/games/views.py
from .models import *   
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, TemplateView , UpdateView 
from .forms import PlayerForm, PromotionForm, RewardForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm


def login_user(request):
    logout(request)
    username = password = ''
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponse("Success")
    return render(request, 'games/login.html')

@login_required(login_url='games/login/')
def main(request):
    return render(request, "games/main.html")

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            form.save()
            user = form.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return HttpResponse("Success")
    else:
        form = UserCreationForm()
    return render(request, 'games/signup.html', {'form': form})
    
def scratch(request):
    return render(request, 'games/scratch.html')


def home(request):
    return HttpResponse("""
    <h1> Bienvenue sur le projet Jeux Promotionnel ! <h1>
    """)

def base(request):
    return render(request, 'games/base.html')

def test(request):
    return render(request, 'games/test.html' )

class GamesChoice(ListView):
    model = Games
    template_name = 'games/gamesChoice.html' 

class GameList(ListView):
    model = Games
    template_name = 'games/games.html'

#-------------- CRUD Player --------------------

class PlayerCreate (CreateView):
    model = Player
    form_class = PlayerForm
    # template_name = 'games/player-create.html'
    success_url = reverse_lazy('games:players')
    template_name = 'games/registration.html'

class PlayerUpdate (UpdateView):
    model = Player
    fields = "__all__"
    template_name = 'games/player-update.html'
    success_url = reverse_lazy('games:players')

class PlayerDelete (DeleteView):
    model = Player
    fields = ['pseudo']
    success_url = reverse_lazy('games:players')
    template_name = 'games/player-delete.html'

class PlayerList(ListView):
    model = Player
    template_name = 'games/players.html'

class PlayerDetail(DetailView):
    model = Player
    fields = '__all__'
    template_name = 'games/player-detail.html'

    def get_context_data(self, **kwargs):
        context = super(PlayerDetail, self).get_context_data(**kwargs)
        context['user'] = Player.objects.get(pk=self.kwargs['pk'])
        return context

#-------------- CRUD Promotion --------------------

class PromotionCreate(CreateView):
    model = Promotion
    form_class = PromotionForm
    success_url = reverse_lazy('games:promotions')
    template_name = 'games/promotion-create.html'

class PromotionDetail(DetailView):
    model = Promotion
    template_name = 'games/promotion-detail.html'

class PromotionList(ListView):
    model = Promotion
    template_name = 'games/promotions.html'

class PromotionUpdate(UpdateView):
    model = Promotion
    form_class = PromotionForm
    success_url = reverse_lazy('games:promotions')
    template_name = 'games/promotion-update.html'

class PromotionDelete(DeleteView):
    model = Promotion
    success_url = reverse_lazy('games:promotions')
    template_name = 'games/promotion-delete.html'

#-------------- CRUD Reward --------------------

class RewardCreate(CreateView):
    model = Reward
    form_class = RewardForm
    success_url = reverse_lazy('games:rewards')
    template_name = 'games/reward-create.html'

class RewardDetail(DetailView):
    model = Reward
    template_name = 'games/reward-detail.html'

class RewardList(ListView):
    model = Reward
    template_name = 'games/rewards.html'

class RewardUpdate(UpdateView):
    model = Reward
    form_class = RewardForm
    success_url = reverse_lazy('games:rewards')
    template_name = 'games/reward-update.html'

class RewardDelete(DeleteView):
    model = Reward
    success_url = reverse_lazy('games:rewards')
    template_name = 'games/reward-delete.html'

jeupromo/games/templates/games/affichageJeux.html
{% extends "games/base.html" %}

{% load static %}

{% block headTitle %}Affichage des jeux{% endblock headTitle %}

{% block css %}{% endblock css %}

{% block titreCadre %}Liste des jeux{% endblock titreCadre %}

{% block content %}


<div class="container blocContenu">
    
    {% if games|length_is:"0" %}
    
    <div>Aucun jeu n'a été ajouté :/</div>
    
    {% else %}
    
    <label>Liste des jeux</label>
    <div class="row enteteTab">
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 ">
            Nom
        </div>
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 ">
            Type
        </div>
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 ">
            Visuel
        </div>
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 ">
            Description
        </div>
    </div>

    {% for game in games %}
    
        <div class="row tabGame">
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 ">
                {{ game.label }}
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 ">
                    {{ game.type }}
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 ">
                {{ game.game_logo }}
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 ">
                {{ game.description }}
            </div>
        </div>
    
    {% endfor %}
    {% endif %}
   
</div>

{% endblock content %}

jeupromo/games/templates/games/base.html
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8" />
    <title>{% block headTitle %}Base html{% endblock headTitle %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'games/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'games/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% block css %}{% endblock css %}">


</head>

<body>
    <div class="container-fluid entete">
        <div class="row">
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4"></div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4" id="logo">
                <img class="logo" src="{% static 'games/img/logo-zerosix.png' %}">
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4"></div>
        </div>
    </div>

    <div class="container encadreTitre">
        <div class="col-xs-12 col-sm-12 col-md-12 col-md-12">
            <h1>{% block titreCadre %}base{% endblock titreCadre %}</h1>
        </div>
    </div>

    {% block content %}{% endblock %}

    <footer class="container footer">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
                <p>Copyright &copy;
                    <a href="http://www.zerosix.com" target="_blank">zerosix</a>
                </p>
            </div>
        </div>
    </footer>
    <!-- jQuery -->
    <script src="{% static 'games/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'games/js/bootstrap.min.js' %}"></script>

</body>

</html>

jeupromo/games/templates/games/gamesChoice.html
{% extends "games/base.html" %}

{% load static %}

{% block headTitle %}gamesChoice{% endblock headTitle %}

{% block css %}
{% static 'games/css/gamesChoice.css' %}
{% endblock css %}

{% block titreCadre %}CHOIX DES JEUX DE VOTRE CAMPAGNE{% endblock titreCadre %}


{% block content %}

<div class="container blocContenu">

{% if object_list|length_is:"0" %}
    <div>Aucun jeu n'a été ajouté</div>
{% else %}
<form action="{% url 'games:gamesChoice' %}">
    {% csrf_token %}
    {% for game in object_list %}

        <div class="row mb-5 tabGame">
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                    <input type="checkbox">{{ game.label }}
        
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                <img src="{{ game.game_logo.url }}" >
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <h5>{{ game.description }}</h5>
            </div>
        </div>

    {% endfor %}

{% endif %}
    <div class="row tabGame">
        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
        </div>
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
            <a href="{% url 'games:test' %}"><span class="btn btn-danger">RETOUR</span></a>
            <div>   </div>
            <button class="btn btn-success">VALIDER</button>
            </form>
        </div>
    </div>
</div>



{% endblock  %}

jeupromo/games/templates/games/login.html
{% extends "games/base.html" %}

{% load static %}

{% block headTitle %}{% endblock headTitle %}

{% block css %}{% endblock css %}

{% block titreCadre %}Login {% endblock titreCadre %}

{% block content %}


<div class="container blocContenu">

        <div id="login">
                <form class="form-horizontal" name="LoginForm" action="{% url 'games:login' %}" method="post">
                {% csrf_token %}
                {% if next %}
                    <input type="hidden" name="next" value="{{ next }}" />
                {% endif %}
                <div class="control-group">
                    <label class="control-label" for="username">Username</label>
                    <div class="controls">
                        <input type="text" id="username" name="username"  placeholder="Username">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="password">Password</label>
                    <div class="controls">
                        <input type="password" name="password" id="password" placeholder="Password">
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <button type="submit" class="btn">Login</button>
                    </div>
                </div>
                </form>
            </div>
   
</div>

{% endblock content %}

jeupromo/games/templates/games/main.html
{% extends "games/base.html" %}

{% load static %}

{% block headTitle %}{% endblock headTitle %}

{% block css %}{% endblock css %}

{% block titreCadre %}test{% endblock titreCadre %}

{% block content %}


<div class="container blocContenu">
        <p>Welcome, {{ user.username }}.</p>
        <a href="{% url 'games:logout' %}">Logout</a>
</div>

{% endblock content %}

jeupromo/games/templates/games/player-detail.html
{% extends 'games/base.html' %}

{% load static %}

{% block headTitle %}Votre profil{% endblock headTitle %}

{% block css %}

{% static 'games/css/player-detail.css' %}

{% endblock css %}

{% block titreCadre %}Votre profil{% endblock titreCadre %}

{% block content %}

{% csrf_token %}

<div class="container blocContenu">  
        <fieldset>
                <div class="row">
                        <div class="col-lg-6 div20">
                        </div>
                        <div  class="col-lg-6 div20">
                                <H2>Avatar : </H2>
                        </div>
                </div>                                 
                <div class="row">
                        <div  class="col-lg-6">
                                <div class="row">
                                        <div  class="col-lg-3">
                                                <label for="gender"> Civilité : </label>        
                                        </div>
                                        <div  class="col-lg-9">
                                                {{ player.gender }}        
                                        </div>    
                                </div>
                                <div class="row">
                                        <div class="col-lg-3">
                                                <label for="name"> Nom : </label>        
                                        </div>
                                        <div class="col-lg-9">
                                                {{ player.user.last_name }}
                                        </div>    
                                </div>
                                <div class="row">
                                        <div class="col-lg-3">
                                                <label for="Firstname"> Prénom : </label>        
                                        </div>
                                        <div class="col-lg-9">
                                                <label for="Firstname">  
                                                        {{ player.user.first_name }}
                                                </label>
                                        </div>    
                                </div>
                                <div class="row">
                                        <div class="col-lg-3">
                                                <label for="email"> Adresse Email : </label>        
                                        </div>
                                        <div class="col-lg-9">
                                                <label for="email">  
                                                        {{ player.user.email }}
                                                </label>
                                        </div>    
                                </div>
                                <div class="row">
                                        <div class="col-lg-3">
                                                <label for="datenaissance"> Date de Naissance : </label>        
                                        </div>
                                        <div class="col-lg-9">
                                                <label for="datenaissance">  
                                                        {{ player.dateNaissance }}
                                                </label>
                                        </div>    
                                </div>
                                <div class="row">
                                        <div class="col-lg-3">
                                                <label for="pseudo"> Pseudo : </label>        
                                        </div>
                                        <div class="col-lg-9">
                                                <label for="pseudo">  
                                                        {{ player.pseudo }}
                                                </label>
                                        </div>    
                                </div>
                        </div>
                        <div  class="col-lg-6">
                                <div >
                                        <img class="img-thumbnail" id="avatar"  src="../../{{ player.avatar.url }}">
                                </div>
                        </div>
                </div>
                <div class="row">
                        <div  class="col-lg-6">
                                <div class="control-group">
                                        <div class="controls">
                                                <button class="btn btn-primary" onclick="window.location.href='http://127.0.0.1:8000/games/test'">Modifier</button>
                                        </div>
                                </div>
                        </div>
                        <div class="col-lg-6"></div> 
                </div> 
        </fieldset>

</div>

{% endblock content %}

jeupromo/games/templates/games/player-update.html
<h1>Player Edit</h1>
<form method = "post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type= "submit" value = "Submit" />
</form>

jeupromo/games/templates/games/promotion-delete.html
<h1>
    suppression OP
</h1>
<form method="post">
    {% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Supprimer promotion" />
</form>

jeupromo/games/templates/games/promotion-update.html
{% extends "games/base.html" %}

{% load static %}

{% block headTitle %}Modification opération promotionnelle{% endblock headTitle %}

{% block css %}{% endblock css %}

{% block titreCadre %}Modification opération promotionnelle{% endblock titreCadre %}

{% block content %}


<div class="container blocContenu">
    
        <form method="post" action="{% url 'games:promotions' %}">
                {% csrf_token %}
        
                <div class="row tabGame ">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mb-5 mt-5">
                        <label>Nom de l'opération promotionnelle:</label>
                        {{ form.name }}
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 mb-5">
                        <label>Date de début:</label>
                        {{form.date_start}}
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 mb-5">
                        <label>Date de fin:</label>
                        {{form.date_end}}
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mb-5">
                        <label>nom de l'administrateur</label>
                        {{ form.name }}
                    </div>
                </div>
        
                <label>Liste des jeux</label>
                <div class="row enteteTab">
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                        Nom
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                        Type
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                        visuel
                    </div>
                </div>
            {% for game in object_list %}
                <div class="row tabGame">
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                        {{ game.label }}
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                        {{ game.type }}
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                        <img src="{{ game.game_logo.url }}">
                    </div>
                </div>
            {% endfor %}
        
            <div class="row tit mb-5">
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                        <a href="{% url 'games:gamesChoice' %}">
                            <span class="btn btn-success">AJOUTER JEU(X)</span>
                        </a>
                    </div>
                </div>
        
                <label>Liste des gains</label>
                    <div class="row enteteTab">
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                            Désignation
                        </div>
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                            Valeur
                        </div>
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                        </div>
                    </div>
                {% for reward in object_list %}
                    <div class="row">
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                            {{ reward.label }}
                        </div>
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                            {{ reward.value }}
                            </div>
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                            <img src="{{ game.game_logo.url }}">
                        </div>
                    </div>
                {% endfor %}
        
                    <div class="row tit mb-5">
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                        </div>
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                        </div>
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">     
                            <a href="{% url 'games:gamesChoice' %}">
                                <span class="btn btn-success">AJOUTER GAIN(S)</span>
                            </a>
                        </div>  
                    </div>
        
                    <div class="row tit">
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                            CREER OPERATION PROMOTIONNELLE ?
                        </div>
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                            <a href="{% url 'games:test' %}"><span class="btn btn-danger">RETOUR</span></a>
                        </div>
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 ">
                            <button class="btn btn-success">VALIDER</button>
                        </div>
                    </div>
    </form>
</div>

{% endblock content %}

jeupromo/games/templates/games/reward-create.html
<h1>creation gain

</h1>
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Ajouter gain" />
</form>

jeupromo/games/templates/games/reward-list.html
{% if object_list|length_is:"0" %}

<div>Aucun gain n'a été ajouté :/</div>

{% else %}

{% for reward in object_list %}
<div>nom: {{reward.label}} valeur:{{reward.value}}</div>

{% endfor %}
{% endif %}

jeupromo/games/templates/games/test.html
{% extends "games/base.html" %}

{% load static %}

{% block headTitle %}{% endblock headTitle %}

{% block css %}{% endblock css %}

{% block titreCadre %}test{% endblock titreCadre %}

{% block content %}


<div class="container blocContenu" >
    
   
   

</div>

{% endblock content %}